### ISSUE TITLE
Running tests results 404 API error 

### ISSUE THREAD

**Issue by chris-gds** [alphagov/whitehall#6274]
## What

Testing failing to run while testing locally

----

````
bundle exec rake
bundle exec rubocop
Inspecting 2005 files
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

2005 files inspected, no offenses detected
yarn run lint
yarn run v1.22.5
$ yarn run lint:js && yarn run lint:scss
$ standardx 'app/assets/javascripts/**/*.js' 'test/javascripts/**/*.js'
$ stylelint app/assets/stylesheets/
✨  Done in 7.93s.
SPEC_OPTS='' /Users/[username]/.rvm/rubies/ruby-2.6.6/bin/ruby -S pact verify --pact-helper /Users/[username]/govuk/whitehall/spec/service_consumers/pact_helper.rb
Error reading file from https://pact-broker.cloudapps.digital/pacts/provider/Whitehall%20API/consumer/GDS%20API%20Adapters/versions/branch-whitehall-api-pact-tests
HTTP request failed: status=404 /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-support-1.15.1/lib/pact/consumer_contract/pact_file.rb:71:in `block in get_remote_with_retry'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-support-1.15.1/lib/pact/consumer_contract/pact_file.rb:60:in `times'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-support-1.15.1/lib/pact/consumer_contract/pact_file.rb:60:in `get_remote_with_retry'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-support-1.15.1/lib/pact/consumer_contract/pact_file.rb:41:in `render_pact'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-support-1.15.1/lib/pact/consumer_contract/pact_file.rb:22:in `read'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_source.rb:17:in `pact_json'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:123:in `collect'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:123:in `pact_jsons'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:80:in `configure_rspec'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:33:in `run'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:76:in `run_with_configured_pacts_from_pact_helper'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:53:in `run_specs'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:13:in `call'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli.rb:32:in `verify'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
/Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/bin/pact:4:in `<top (required)>'
/Users/[username]/.rvm/gems/ruby-2.6.6/bin/pact:23:in `load'
/Users/[username]/.rvm/gems/ruby-2.6.6/bin/pact:23:in `<main>'
Traceback (most recent call last):
	21: from /Users/[username]/.rvm/gems/ruby-2.6.6/bin/pact:23:in `<main>'
	20: from /Users/[username]/.rvm/gems/ruby-2.6.6/bin/pact:23:in `load'
	19: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/bin/pact:4:in `<top (required)>'
	18: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	17: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	16: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	15: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	14: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli.rb:32:in `verify'
	13: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:13:in `call'
	12: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
	11: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:53:in `run_specs'
	10: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/cli/run_pact_verification.rb:76:in `run_with_configured_pacts_from_pact_helper'
	 9: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:33:in `run'
	 8: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:80:in `configure_rspec'
	 7: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:123:in `pact_jsons'
	 6: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_spec_runner.rb:123:in `collect'
	 5: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-1.57.0/lib/pact/provider/pact_source.rb:17:in `pact_json'
	 4: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-support-1.15.1/lib/pact/consumer_contract/pact_file.rb:22:in `read'
	 3: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-support-1.15.1/lib/pact/consumer_contract/pact_file.rb:41:in `render_pact'
	 2: from /Users/[username]/.rvm/gems/ruby-2.6.6/gems/pact-support-1.15.1/lib/pact/consumer_contract/pact_file.rb:60:in `get_remote_with_retry'

**Comment by ChrisBAshton** [comment]
Looks like it's fixed now, on latest:

```
$ cd ~/govuk/govuk-docker

$ make whitehall

$ cd ~/govuk/whitehall

$ govuk-docker-run bundle exec rake test
```
