### ISSUE TITLE
Page failing to render locally - Announcements 

### ISSUE THREAD

**Issue by chris-gds** [alphagov/whitehall#6277]
## What

Trying to visit this page
http://whitehall-frontend.dev.gov.uk/government/announcements.ka?world_locations%5B%5D=algeria

### Screenshot

![image](https://user-images.githubusercontent.com/71266765/132852467-32996e53-da38-458e-ba6c-a9831a9dff2a.png)

---

## Stack trace

[`search-api`](https://github.com/alphagov/search-api) running in parallel

```search-api-app_1                            |  INFO  Services : GET http://elasticsearch-6:9200/govuk/_alias [status:200, request:0.007s, query:n/a]
search-api-app_1                            |  INFO  Services : GET http://elasticsearch-6:9200/govuk/_alias [status:200, request:0.006s, query:n/a]
search-api-app_1                            |  INFO  Services : GET http://elasticsearch-6:9200/detailed,government,govuk/generic-document/_search [status:200, request:0.019s, query:0.011s]
search-api-app_1                            | 172.18.0.8 - - [10/Sep/2021:11:59:50 +0000] "GET /search.json?order=-public_timestamp&count=2&fields[]=display_type&fields[]=title&fields[]=link&fields[]=public_timestamp&fields[]=format&fields[]=content_store_document_type&fields[]=description&fields[]=content_id&fields[]=organisations&fields[]=document_collections&filter_content_store_document_type[]=press_release&filter_content_store_document_type[]=news_article&filter_content_store_document_type[]=news_story&filter_content_store_document_type[]=fatality_notice&filter_content_store_document_type[]=speech&filter_content_store_document_type[]=written_statement&filter_content_store_document_type[]=oral_statement&filter_content_store_document_type[]=authored_article&filter_content_store_document_type[]=government_response&filter_content_store_document_type[]=world_news_story&filter_world_locations=france HTTP/1.0" 200 135 0.0381
```
---

[`content-store`](https://github.com/alphagov/content-store) running in parallel

```Attaching to govuk-docker_content-store-app_1
content-store-app_1                         | => Booting WEBrick
content-store-app_1                         | => Rails 5.2.4.4 application starting in development on http://localhost:3000
content-store-app_1                         | => Run `rails server -h` for more startup options
content-store-app_1                         | [2021-09-10 12:39:17] INFO  WEBrick 1.6.0
content-store-app_1                         | [2021-09-10 12:39:17] INFO  ruby 2.6.6 (2020-03-31) [x86_64-linux]
content-store-app_1                         | [2021-09-10 12:39:17] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
```

---

```
whitehall-app_1                             | Started GET "/government/announcements.ka?world_locations%5B%5D=algeria" for 172.18.0.8 at 2021-09-10 12:22:01 +0000
whitehall-app_1                             | Processing by AnnouncementsController#index as HTML
whitehall-app_1                             |   Parameters: {"world_locations"=>["algeria"], "locale"=>"ka"}
whitehall-app_1                             |   Announcement Load (1.9ms)  SELECT `editions`.`id`, `editions`.`created_at`, `editions`.`updated_at`, `editions`.`lock_version`, `editions`.`document_id`, `editions`.`state`, `editions`.`type`, `editions`.`role_appointment_id`, `editions`.`location`, `editions`.`delivered_on`, `editions`.`major_change_published_at`, `editions`.`first_published_at`, `editions`.`speech_type_id`, `editions`.`stub`, `editions`.`change_note`, `editions`.`force_published`, `editions`.`minor_change`, `editions`.`publication_type_id`, `editions`.`related_mainstream_content_url`, `editions`.`related_mainstream_content_title`, `editions`.`additional_related_mainstream_content_url`, `editions`.`additional_related_mainstream_content_title`, `editions`.`alternative_format_provider_id`, `editions`.`public_timestamp`, `editions`.`scheduled_publication`, `editions`.`replaces_businesslink`, `editions`.`access_limited`, `editions`.`published_major_version`, `editions`.`published_minor_version`, `editions`.`operational_field_id`, `editions`.`roll_call_introduction`, `editions`.`news_article_type_id`, `editions`.`relevant_to_local_government`, `editions`.`person_override`, `editions`.`external`, `editions`.`external_url`, `editions`.`opening_at`, `editions`.`closing_at`, `editions`.`corporate_information_page_type_id`, `editions`.`primary_locale`, `editions`.`political`, `editions`.`logo_url`, `editions`.`read_consultation_principles`, `editions`.`all_nation_applicability`, `editions`.`image_display_option` FROM `editions` WHERE `editions`.`type` = 'Announcement' AND `editions`.`state` != 'deleted' AND `editions`.`state` = 'scheduled' ORDER BY scheduled_publication asc
whitehall-app_1                             |   ↳ app/helpers/cache_control_helper.rb:7:in `map'
whitehall-app_1                             |   WorldLocation Exists? (1.0ms)  SELECT 1 AS one FROM `world_locations` WHERE `world_locations`.`slug` = 'algeria' LIMIT 1
whitehall-app_1                             |   ↳ lib/whitehall/document_filter/mysql.rb:113:in `filter_by_location!'
whitehall-app_1                             |   WorldLocation Load (1.1ms)  SELECT `world_locations`.`id`, `world_locations`.`created_at`, `world_locations`.`updated_at`, `world_locations`.`slug`, `world_locations`.`active`, `world_locations`.`world_location_type_id`, `world_locations`.`iso2`, `world_locations`.`analytics_identifier`, `world_locations`.`content_id`, `world_locations`.`news_page_content_id` FROM `world_locations` WHERE `world_locations`.`slug` = 'algeria'
whitehall-app_1                             |   ↳ lib/whitehall/document_filter/mysql.rb:119:in `map'
whitehall-app_1                             |    (2.0ms)  SELECT `editions`.`id` FROM `editions` INNER JOIN `edition_translations` ON `edition_translations`.`edition_id` = `editions`.`id` LEFT OUTER JOIN `documents` ON `documents`.`id` = `editions`.`document_id` LEFT OUTER JOIN `edition_organisations` ON `edition_organisations`.`edition_id` = `editions`.`id` LEFT OUTER JOIN `organisations` ON `organisations`.`id` = `edition_organisations`.`organisation_id` INNER JOIN `edition_world_locations` ON `edition_world_locations`.`edition_id` = `editions`.`id`
whitehall-app_1                             | INNER JOIN `world_locations` ON `world_locations`.`id` = `edition_world_locations`.`world_location_id` WHERE `editions`.`type` = 'Announcement' AND `editions`.`state` != 'deleted' AND `editions`.`state` = 'published' AND `edition_translations`.`locale` = 'ka' AND `world_locations`.`id` = 3
whitehall-app_1                             |   ↳ app/models/edition.rb:149:in `in_reverse_chronological_order'
whitehall-app_1                             |
whitehall-app_1                             | GdsApi::HTTPUnavailable (URL: http://content-store.dev.gov.uk/content/government/announcements
whitehall-app_1                             | Response body:
whitehall-app_1                             | <html>
whitehall-app_1                             | <head><title>503 Service Temporarily Unavailable</title></head>
whitehall-app_1                             | <body>
whitehall-app_1                             | <center><h1>503 Service Temporarily Unavailable</h1></center>
whitehall-app_1                             | <hr><center>nginx</center>
whitehall-app_1                             | </body>
whitehall-app_1                             | </html>
whitehall-app_1                             | ):
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gds-api-adapters-73.0.0/lib/gds_api/json_client.rb:108:in `rescue in do_json_request'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gds-api-adapters-73.0.0/lib/gds_api/json_client.rb:96:in `do_json_request'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gds-api-adapters-73.0.0/lib/gds_api/json_client.rb:52:in `get_json'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/2.6.0/forwardable.rb:230:in `get_json'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gds-api-adapters-73.0.0/lib/gds_api/content_store.rb:14:in `content_item'
whitehall-app_1                             | /govuk/whitehall/app/controllers/announcements_controller.rb:16:in `block (2 levels) in index'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
whitehall-app_1                             | /govuk/whitehall/app/controllers/announcements_controller.rb:12:in `index'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/abstract_controller/base.rb:228:in `process_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
whitehall-app_1                             | /govuk/whitehall/app/controllers/public_facing_controller.rb:59:in `set_locale'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `block in instrument'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `instrument'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/abstract_controller/base.rb:165:in `process'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionview-6.1.4.1/lib/action_view/rendering.rb:39:in `process'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/metal.rb:190:in `dispatch'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/metal.rb:254:in `dispatch'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/journey/router.rb:32:in `each'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/journey/router.rb:32:in `serve'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/routing/route_set.rb:842:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/slimmer-15.6.1/lib/slimmer/app.rb:33:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sentry-rails-4.5.2/lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gds-api-adapters-73.0.0/lib/gds_api/middleware/govuk_header_sniffer.rb:12:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gds-api-adapters-73.0.0/lib/gds_api/middleware/govuk_header_sniffer.rb:12:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gds-api-adapters-73.0.0/lib/gds_api/middleware/govuk_header_sniffer.rb:12:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gds-api-adapters-73.0.0/lib/gds_api/middleware/govuk_header_sniffer.rb:12:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/gds-api-adapters-73.0.0/lib/gds_api/middleware/govuk_header_sniffer.rb:12:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:202:in `call!'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:169:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/omniauth-2.0.4/lib/omniauth/builder.rb:45:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/cookies.rb:689:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4.1/lib/active_record/migration.rb:601:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/better_errors-2.7.1/lib/better_errors/middleware.rb:59:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/rack/logger.rb:37:in `call_app'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/rack/logger.rb:26:in `block in call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/tagged_logging.rb:37:in `tagged'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/tagged_logging.rb:99:in `tagged'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/rack/logger.rb:26:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sentry-ruby-core-4.5.2/lib/sentry/rack/capture_exceptions.rb:23:in `block in call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sentry-ruby-core-4.5.2/lib/sentry/hub.rb:56:in `with_scope'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sentry-ruby-core-4.5.2/lib/sentry-ruby.rb:168:in `with_scope'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sentry-ruby-core-4.5.2/lib/sentry/rack/capture_exceptions.rb:14:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/static.rb:24:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/invalid_utf8_rejector-0.0.4/lib/invalid_utf8_rejector/middleware.rb:11:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack_strip_client_ip-0.0.2/lib/rack_strip_client_ip/middleware.rb:8:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/engine.rb:539:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:207:in `public_send'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:207:in `method_missing'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/configuration.rb:249:in `call'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/request.rb:77:in `block in handle_request'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/request.rb:76:in `handle_request'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/server.rb:438:in `process_client'
whitehall-app_1                             | /root/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
whitehall-app_1                             |
whitehall-app_1                             |
whitehall-app_1                             |   Rendering text template
whitehall-app_1                             |   Rendered text template (Duration: 0.1ms | Allocations: 2)
whitehall-app_1                             | Completed 500 Internal Server Error in 82ms (Views: 3.7ms | ActiveRecord: 6.0ms | Allocations: 11418)
whitehall-app_1                             |
whitehall-app_1                             | 
```

**Comment by ChrisBAshton** [comment]
The page no longer seems to exist. Closing.
